class ClassesList {
  final Map<String, String> classNames = {
    '0': 'Apple Scab (Apple)',
    '1': 'Black Rot (Apple)',
    '2': 'Cedar Apple Rust (Apple)',
    '3': 'Healthy (Apple)',
    '4': 'No Leaf Found',
    '5': 'Healthy (Blueberry)',
    '6': 'Present (Caterpillar)',
    '7': 'Powdery Mildew (Cherry)',
    '8': 'Healthy (Cherry)',
    '9': 'Cercospora Leaf Spot / Gray Leaf Spot (Corn)',
    '10': 'Common Rust (Corn)',
    '11': 'Northern Leaf Blight (Corn)',
    '12': 'Healthy (Corn)',
    '13': 'Black Rot (Grape)',
    '14': 'Esca (Black Measles) (Grape)',
    '15': 'Leaf Blight (Isariopsis Leaf Spot) (Grape)',
    '16': 'Healthy (Grape)',
    '17': 'Abiotic Disease (Maize)',
    '18': 'Aphids (Maize)',
    '19': 'Curvularia (Maize)',
    '20': 'Healthy Leaf (Maize)',
    '21': 'Helminthosporiosis (Maize)',
    '22': 'Rust (Maize)',
    '23': 'Spodoptera Frugiperda (P) (Maize)',
    '24': 'Spodoptera Frugiperda (A) (Maize)',
    '25': 'Stripe (Maize)',
    '26': 'Virosis (Maize)',
    '27': 'Alternaria (Onion)',
    '28': 'Bulb Blight (Onion)',
    '29': 'Fusarium (Onion)',
    '30': 'Healthy Leaf (Onion)',
    '31': 'Virosis (Onion)',
    '32': 'Huanglongbing (Citrus Greening) (Orange)',
    '33': 'Bacterial Spot (Peach)',
    '34': 'Healthy (Peach)',
    '35': 'Bacterial Spot (Pepper, Bell)',
    '36': 'Healthy (Pepper, Bell)',
    '37': 'Early Blight (Potato)',
    '38': 'Late Blight (Potato)',
    '39': 'Healthy (Potato)',
    '40': 'Healthy (Raspberry)',
    '41': 'Healthy (Soybean)',
    '42': 'Powdery Mildew (Squash)',
    '43': 'Leaf Scorch (Strawberry)',
    '44': 'Healthy (Strawberry)',
    '45': 'Bacterial Spot (Tomato)',
    '46': 'Early Blight (Tomato)',
    '47': 'Late Blight (Tomato)',
    '48': 'Leaf Mold (Tomato)',
    '49': 'Septoria Leaf Spot (Tomato)',
    '50': 'Spider Mites (Two-Spotted Spider Mite) (Tomato)',
    '51': 'Target Spot (Tomato)',
    '52': 'Tomato Yellow Leaf Curl Virus (Tomato)',
    '53': 'Tomato Mosaic Virus (Tomato)',
    '54': 'Healthy (Tomato)',
  };

  String getClassName(String classId) {
    return classNames[classId] ?? "Unknown Class";
  }
}
