name: AgriVision
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  http: ^1.3.0
  pinput: ^5.0.1
  image_picker: ^1.1.2
  permission_handler: ^11.4.0
  camera: ^0.11.0+2
  image: ^4.5.3
  tflite_flutter: ^0.11.0
  geolocator: ^13.0.2
  shared_preferences: ^2.3.5
  connectivity_plus: ^6.1.3
  flutter_local_notifications: ^18.0.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/languages/
    - assets/images/
    - assets/models/

  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700